import re
import logging
from pydantic import BaseModel, Field, field_validator, ValidationError

# -------------------------------------------------------------
# 1. INPUT GUARDRAIL: The Bouncer
# -------------------------------------------------------------
def validate_input(user_query: str) -> tuple[bool, str]:
    """
    Checks the user query for prompt injections or severe off-topic requests 
    before wasting compute on vector search or LLM generation.
    """
    query_lower = user_query.lower()

    # Block 1: Jailbreak & Prompt Injection attempts
    injections = [
        "ignore all previous", "forget your instructions", "system prompt", 
        "bypass", "you are now", "write a python script", "delete the database", 
        "you are now"
    ]
    if any(inj in query_lower for inj in injections):
        logging.warning(f"[GUARDRAIL BLOCKED] Prompt injection attempt: {user_query}")
        return False, "I cannot fulfill this request. Please ask a question related to IPCC climate science."

    # Block 2: Length boundary (prevents token overflow attacks)
    if len(user_query) > 500:
        logging.warning(f"[GUARDRAIL BLOCKED] Query too long: {len(user_query)} chars")
        return False, "Your question is too long. Please condense it to under 500 characters."

    return True, ""


# -------------------------------------------------------------
# 2. OUTPUT GUARDRAIL: The Editor (Pydantic)
# -------------------------------------------------------------
class IPCCAnswer(BaseModel):
    """
    Forces the LLM output into a strict schema. If the LLM returns text 
    without citations, the Pydantic validator throws an error.
    """
    answer_text: str = Field(description="The scientific answer generated by the LLM.")

    @field_validator("answer_text")
    def enforce_citations(cls, value):
        # Regex to check if the answer contains at least one citation like [1] or [2]
        citation_pattern = re.compile(r"\[\d+\]")
        
        # If the LLM says it doesn't have enough info, let it pass
        if "do not have enough information" in value.lower():
            return value

        # If it tries to give a factual answer without a citation, block it
        if not citation_pattern.search(value):
            raise ValueError("Output Guardrail Triggered: The model generated a claim without citing a source bracket (e.g., [1]).")
        
        return value

def validate_output(llm_response_text: str) -> str:
    """
    Wraps the LLM output in the Pydantic validator.
    """
    try:
        validated_data = IPCCAnswer(answer_text=llm_response_text)
        return validated_data.answer_text
    except ValidationError as e:
        logging.error(f"[GUARDRAIL TRIGGERED] Output validation failed: {e}")
        # Fallback response if the LLM hallucinated ungrounded text
        return "I generated an answer, but it was blocked by safety guardrails because it could not be properly cited to the provided IPCC documents."